In [2]:
# %pip install -U spacy
# %pip install -U spacy-lookups-data

# !python3 -m spacy download en_core_web_sm

Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.
Defaulting to 

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("../data/spam.csv", encoding= 'latin-1', usecols=['v1', 'v2'])

In [5]:
data.columns = ["label", "text"]
data.head()

label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
data['label'] = data['label'].map({"ham": 0, "spam":1})

In [7]:
import spacy
nlp = spacy.load("en_core_web_sm")

# Задание 4

In [8]:
from sklearn.decomposition import LatentDirichletAllocation

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
n_features = 25

tf_vectorizer = CountVectorizer(max_df=.95, min_df=10,
                                max_features=n_features,
                                stop_words='english')

In [22]:
tf = tf_vectorizer.fit_transform(data['text'])

In [40]:
tf.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
tf.toarray()[0]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [35]:
tf.toarray()[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0])

In [36]:
tf.toarray()[2]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0])

In [34]:
tf.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [32]:
tf_vectorizer.vocabulary_

{'got': 6,
 'ok': 17,
 'free': 3,
 'text': 20,
 'txt': 22,
 'don': 2,
 'like': 11,
 'send': 18,
 'home': 8,
 'want': 24,
 'day': 1,
 'ur': 23,
 'going': 4,
 'lor': 13,
 'just': 9,
 'love': 14,
 'll': 12,
 'know': 10,
 'need': 16,
 'lt': 15,
 'gt': 7,
 'time': 21,
 'sorry': 19,
 'good': 5,
 'come': 0}

In [26]:
tf

<5572x25 sparse matrix of type '<class 'numpy.int64'>'
	with 5307 stored elements in Compressed Sparse Row format>

In [23]:
tf_vectorizer.get_feature_names_out()

array(['come', 'day', 'don', 'free', 'going', 'good', 'got', 'gt', 'home',
       'just', 'know', 'like', 'll', 'lor', 'love', 'lt', 'need', 'ok',
       'send', 'sorry', 'text', 'time', 'txt', 'ur', 'want'], dtype=object)

In [12]:
tf.shape

(5572, 20)

In [13]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-n_top_words - 1:-1]]))

In [14]:
lda = LatentDirichletAllocation(n_components=10, max_iter=20,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0).fit(tf)

In [24]:
lda.components_

array([[1.00003744e-01, 1.00002943e-01, 2.84889791e+02, 1.00002236e-01,
        1.00001269e-01, 1.00002506e-01, 1.00001397e-01, 1.00005020e-01,
        1.00002167e-01, 1.00004394e-01, 1.00002897e-01, 1.00002387e-01,
        1.00001324e-01, 1.00004511e-01, 1.60196394e+02, 1.00007411e-01,
        2.20535307e+02, 1.00034281e-01, 1.00004519e-01, 1.00006233e-01],
       [1.00002162e-01, 2.29123842e+02, 1.00006926e-01, 1.00001181e-01,
        1.00005113e-01, 1.00001876e-01, 1.00001809e-01, 1.00004755e-01,
        1.00003265e-01, 1.00006699e-01, 1.00002320e-01, 1.00009250e-01,
        1.00001584e-01, 1.00003664e-01, 3.59318990e+01, 1.00002258e-01,
        1.00003245e-01, 1.00064125e-01, 3.81292294e+02, 1.00001733e-01],
       [1.00000537e-01, 1.00002378e-01, 1.00462764e-01, 1.00000768e-01,
        1.00000413e-01, 1.00001157e-01, 1.00000344e-01, 1.00006321e-01,
        1.00001890e-01, 1.00002802e-01, 1.00004359e-01, 1.00002629e-01,
        1.00000343e-01, 1.00001742e-01, 1.00008640e-01, 1.9504

In [18]:
for topic_idx, topic in enumerate(lda.components_):
        print("Topic #%d:" % topic_idx)
        # print(topic)
        print(topic.argsort())
        print(topic.argsort()[:-10:])
        print(topic.argsort()[:-10 - 1:])
        print(topic.argsort()[:-10 - 1:-1])
        # print(topic.argsort()[:-10 - 1:-1])
        print('..................')
        # for i in topic.argsort()[:-10 - 1:-1]:
                
        # print(" ".join([feature_names[i]
        #                 for i in topic.argsort()[:-n_top_words - 1:-1]]))

Topic #0:
[ 4 12  6  8  3 11  5 10  1  0  9 13 18  7 19 15 17 14 16  2]
[ 4 12  6  8  3 11  5 10  1  0]
[ 4 12  6  8  3 11  5 10  1]
[ 2 16 14 17 15 19  7 18 13  9]
..................
Topic #1:
[ 3 12 19  6  5  0 15 10 16  8 13  7  4  9  2 11 17 14  1 18]
[ 3 12 19  6  5  0 15 10 16  8]
[ 3 12 19  6  5  0 15 10 16]
[18  1 14 17 11  2  9  4  7 13]
..................
Topic #2:
[12  6  4  0  3  5 13  8  1 11  9 16 10  7 19 14 18  2 17 15]
[12  6  4  0  3  5 13  8  1 11]
[12  6  4  0  3  5 13  8  1]
[15 17  2 18 14 19  7 10 16  9]
..................
Topic #3:
[15 17  4  8  6 12  1  2 14 13 10  7 11 18 19 16  3  9  0  5]
[15 17  4  8  6 12  1  2 14 13]
[15 17  4  8  6 12  1  2 14]
[ 5  0  9  3 16 19 18 11  7 10]
..................
Topic #4:
[15  2 13 12  6  0 18  4 10  5  7 19 17 16  1  8 14  3 11  9]
[15  2 13 12  6  0 18  4 10  5]
[15  2 13 12  6  0 18  4 10]
[ 9 11  3 14  8  1 16 17 19  7]
..................
Topic #5:
[17  4 13 18  5 12  6  0  3 11  1  2  9 14 19 15  7 16  8 10]
[17  4 1

In [16]:
print_top_words(lda, tf_vectorizer.get_feature_names_out(), 10) # выводим топ 10 слов

Topic #0:
free time send txt text want just ur ok like
Topic #1:
ur day send txt love free like good just ok
Topic #2:
text txt free ur send want just ll time like
Topic #3:
got come like going time want ur love just ll
Topic #4:
like love going send know day time txt want just
Topic #5:
ll know time just text want send like free day
Topic #6:
good day love time send just know ur going got
Topic #7:
just want send know got text love like free time
Topic #8:
gt lt like time send know ll want day got
Topic #9:
ok ur time ll going like send come got just


## BoW implementation

# Задание 1

In [17]:
n_features = 25


tf_vectorizer = CountVectorizer(max_df=.95, min_df=10,
                                max_features=n_features,
                                stop_words='english')

In [18]:
tf_ar = tf_vectorizer.fit_transform(data['text']).A

In [19]:
tf_ar

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
tf_vectorizer.get_feature_names_out()

array(['come', 'day', 'don', 'free', 'going', 'good', 'got', 'gt', 'home',
       'just', 'know', 'like', 'll', 'lor', 'love', 'lt', 'need', 'ok',
       'send', 'sorry', 'text', 'time', 'txt', 'ur', 'want'], dtype=object)

In [21]:
tf_df = pd.DataFrame(tf_ar, columns=tf_vectorizer.get_feature_names_out())
tf_df

come  day  don  free  going  good  got  gt  home  just  ...  lt  need  \
0        0    0    0     0      0     0    1   0     0     0  ...   0     0   
1        0    0    0     0      0     0    0   0     0     0  ...   0     0   
2        0    0    0     1      0     0    0   0     0     0  ...   0     0   
3        0    0    0     0      0     0    0   0     0     0  ...   0     0   
4        0    0    1     0      0     0    0   0     0     0  ...   0     0   
...    ...  ...  ...   ...    ...   ...  ...  ..   ...   ...  ...  ..   ...   
5567     0    0    0     0      0     0    0   0     0     0  ...   0     0   
5568     0    0    0     0      1     0    0   0     1     0  ...   0     0   
5569     0    0    0     0      0     0    0   0     0     0  ...   0     0   
5570     0    0    0     1      0     0    0   0     0     0  ...   0     0   
5571     0    0    0     0      0     0    0   0     0     0  ...   0     0   

      ok  send  sorry  text  time  txt  ur  want  
0      0     0      0     0     0    0   0     0  
1      1     0      0     0     0    0   0     0  
2      0     0      0     1     0    1   0     0  
3      0     0      0     0     0    0   0     0  
4      0     0      0     0     0    0   0     0  
...   ..   ...    ...   ...   ...  ...  ..   ...  
5567   0     0      0     0     1    0   0     0  
5568   0     0      0     0     0    0   0     0  
5569   0     0      0     0     0    0   0     0  
5570   0     0      0     0     0    0   0     0  
5571   0     0      0     0     0    0   0     0  

[5572 rows x 25 columns]

In [22]:
from sklearn.decomposition import PCA

classification_df = pd.concat([data['label'], tf_df], axis=1)
classification_df

label  come  day  don  free  going  good  got  gt  home  ...  lt  need  \
0         0     0    0    0     0      0     0    1   0     0  ...   0     0   
1         0     0    0    0     0      0     0    0   0     0  ...   0     0   
2         1     0    0    0     1      0     0    0   0     0  ...   0     0   
3         0     0    0    0     0      0     0    0   0     0  ...   0     0   
4         0     0    0    1     0      0     0    0   0     0  ...   0     0   
...     ...   ...  ...  ...   ...    ...   ...  ...  ..   ...  ...  ..   ...   
5567      1     0    0    0     0      0     0    0   0     0  ...   0     0   
5568      0     0    0    0     0      1     0    0   0     1  ...   0     0   
5569      0     0    0    0     0      0     0    0   0     0  ...   0     0   
5570      0     0    0    0     1      0     0    0   0     0  ...   0     0   
5571      0     0    0    0     0      0     0    0   0     0  ...   0     0   

      ok  send  sorry  text  time  txt  ur  want  
0      0     0      0     0     0    0   0     0  
1      1     0      0     0     0    0   0     0  
2      0     0      0     1     0    1   0     0  
3      0     0      0     0     0    0   0     0  
4      0     0      0     0     0    0   0     0  
...   ..   ...    ...   ...   ...  ...  ..   ...  
5567   0     0      0     0     1    0   0     0  
5568   0     0      0     0     0    0   0     0  
5569   0     0      0     0     0    0   0     0  
5570   0     0      0     0     0    0   0     0  
5571   0     0      0     0     0    0   0     0  

[5572 rows x 26 columns]

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

X_pca = pca.fit_transform(classification_df.drop('label', axis=1), classification_df["label"])
X_pca

array([[-0.07661339, -0.10051096],
       [-0.09520684, -0.07812336],
       [-0.10912399,  0.31094308],
       ...,
       [-0.08334393, -0.09089606],
       [-0.07233871,  0.09881086],
       [-0.08334393, -0.09089606]])

In [24]:
import numpy as np

In [25]:
from scipy.stats import mode 

class K_Nearest_Neighbors_Classifier() :  
      
    def __init__( self, K ) : 
          
        self.K = K 
                    
    def fit( self, X_train, Y_train ) : 
          
        self.X_train = X_train 
          
        self.Y_train = Y_train 
                    
        self.m, self.n = X_train.shape 
                
    def predict( self, X_test ) : 
          
        self.X_test = X_test 
                    
        self.m_test, self.n = X_test.shape 
                    
        Y_predict = np.zeros( self.m_test ) 
          
        for i in range( self.m_test ) : 
              
            x = self.X_test[i] 
                                          
            neighbors = self.find_neighbors( x ) 
                            
            Y_predict[i] = mode( neighbors )[0][0]     
              
        return Y_predict 
                  
    def find_neighbors( self, x ) : 
          
        euclidean_distances = np.zeros( self.m ) 
          
        for i in range( self.m ) : 
              
            d = self.euclidean( x, self.X_train[i] ) 
              
            euclidean_distances[i] = d 
        
        inds = euclidean_distances.argsort() # берём по порядку от самого маленького до самого большого расстояния по индексам
        Y_train_sorted = self.Y_train[inds]        

        return Y_train_sorted[:self.K] 
      
    # Function to calculate euclidean distance 
              
    def euclidean( self, x, x_train ) : 
          
        return np.sqrt( np.sum( np.square( x - x_train ) ) ) 



In [26]:
from sklearn.model_selection import train_test_split

In [27]:
np.array(classification_df['label'])

array([0, 0, 1, ..., 0, 0, 0])

In [28]:
knn = K_Nearest_Neighbors_Classifier(K=3)

X_train, X_test, y_train, y_test = train_test_split(X_pca, np.array(classification_df['label']), 
                                                    test_size= .3)
knn.fit(X_train, y_train)

In [29]:
y_pred = knn.predict(X_test)

/tmp/ipykernel_3661/2046311215.py:31: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  Y_predict[i] = mode( neighbors )[0][0]


In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [31]:
accuracy_score(y_pred, y_test)

0.9049043062200957

In [32]:
confusion_matrix(y_pred, y_test)

array([[1422,  109],
       [  50,   91]])